/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IIdentityVerifier, IIdentityVerifierInterface } from "../../interfaces/IIdentityVerifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "proof",
        "type": "bytes"
      },
      {
        "internalType": "bytes32",
        "name": "identityHash",
        "type": "bytes32"
      }
    ],
    "name": "verify",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IIdentityVerifier__factory {
    static readonly abi = _abi;
    static createInterface(): IIdentityVerifierInterface {
      return new Interface(_abi) as IIdentityVerifierInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IIdentityVerifier {
      return new Contract(address, _abi, runner) as unknown as IIdentityVerifier;
    }
  }
  