// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IIdentityVerifier$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IIdentityVerifier";
  readonly sourceName: "contracts/interfaces/IIdentityVerifier.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes","name":"proof","type":"bytes"},{"internalType":"bytes32","name":"identityHash","type":"bytes32"}],"name":"verify","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IIdentityVerifier.sol";
  readonly buildInfoId: "solc-0_8_28-125afb21dd07dbde7743e4800a9b4cbe7b4e0a33";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IIdentityVerifier"]: IIdentityVerifier$Type;
    ["contracts/interfaces/IIdentityVerifier.sol:IIdentityVerifier"]: IIdentityVerifier$Type;
  }
}