/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IReputationInterface extends Interface {
    getFunction(nameOrSignature: "reputation"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'reputation', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'reputation', data: BytesLike): Result;
  }

  

  export interface IReputation extends BaseContract {
    
    connect(runner?: ContractRunner | null): IReputation;
    waitForDeployment(): Promise<this>;

    interface: IReputationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    reputation: TypedContractMethod<
      [artist: AddressLike, ],
      [[bigint, bigint, bigint] & {chunksServed: bigint, uniqueFans: bigint, reputationScore: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'reputation'): TypedContractMethod<
      [artist: AddressLike, ],
      [[bigint, bigint, bigint] & {chunksServed: bigint, uniqueFans: bigint, reputationScore: bigint }],
      'view'
    >;

    

    filters: {
      
    };
  }