/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface BansheeReputationInterface extends Interface {
    getFunction(nameOrSignature: "recordReceipt" | "reputation" | "trackerOracle"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ReceiptRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'recordReceipt', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'reputation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'trackerOracle', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'recordReceipt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'trackerOracle', data: BytesLike): Result;
  }

  
    export namespace ReceiptRecordedEvent {
      export type InputTuple = [artist: AddressLike, fan: AddressLike, chunks: BigNumberish];
      export type OutputTuple = [artist: string, fan: string, chunks: bigint];
      export interface OutputObject {artist: string, fan: string, chunks: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BansheeReputation extends BaseContract {
    
    connect(runner?: ContractRunner | null): BansheeReputation;
    waitForDeployment(): Promise<this>;

    interface: BansheeReputationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    recordReceipt: TypedContractMethod<
      [artist: AddressLike, fan: AddressLike, chunks: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reputation: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint] & {chunksServed: bigint, uniqueFans: bigint, reputationScore: bigint }],
      'view'
    >
    

    
    trackerOracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'recordReceipt'): TypedContractMethod<
      [artist: AddressLike, fan: AddressLike, chunks: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputation'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint] & {chunksServed: bigint, uniqueFans: bigint, reputationScore: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'trackerOracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'ReceiptRecorded'): TypedContractEvent<ReceiptRecordedEvent.InputTuple, ReceiptRecordedEvent.OutputTuple, ReceiptRecordedEvent.OutputObject>;

    filters: {
      
      'ReceiptRecorded(address,address,uint256)': TypedContractEvent<ReceiptRecordedEvent.InputTuple, ReceiptRecordedEvent.OutputTuple, ReceiptRecordedEvent.OutputObject>;
      ReceiptRecorded: TypedContractEvent<ReceiptRecordedEvent.InputTuple, ReceiptRecordedEvent.OutputTuple, ReceiptRecordedEvent.OutputObject>;
    
    };
  }