/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'BansheeMining', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BansheeMining__factory>
getContractFactory(name: 'BansheeToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BansheeToken__factory>
getContractFactory(name: 'IReputation', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IReputation__factory>
getContractFactory(name: 'BansheeReputation', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BansheeReputation__factory>
getContractFactory(name: 'BansheeTicketMarketplace', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BansheeTicketMarketplace__factory>
getContractFactory(name: 'IIdentityVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IIdentityVerifier__factory>
getContractFactory(name: 'MockIdentityVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockIdentityVerifier__factory>

  getContractAt(name: 'BansheeMining', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BansheeMining>
getContractAt(name: 'BansheeToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BansheeToken>
getContractAt(name: 'IReputation', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IReputation>
getContractAt(name: 'BansheeReputation', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BansheeReputation>
getContractAt(name: 'BansheeTicketMarketplace', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BansheeTicketMarketplace>
getContractAt(name: 'IIdentityVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IIdentityVerifier>
getContractAt(name: 'MockIdentityVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockIdentityVerifier>

  deployContract(name: 'BansheeMining', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BansheeMining>
deployContract(name: 'BansheeToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BansheeToken>
deployContract(name: 'IReputation', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReputation>
deployContract(name: 'BansheeReputation', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BansheeReputation>
deployContract(name: 'BansheeTicketMarketplace', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BansheeTicketMarketplace>
deployContract(name: 'IIdentityVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IIdentityVerifier>
deployContract(name: 'MockIdentityVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockIdentityVerifier>

  deployContract(name: 'BansheeMining', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BansheeMining>
deployContract(name: 'BansheeToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BansheeToken>
deployContract(name: 'IReputation', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReputation>
deployContract(name: 'BansheeReputation', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BansheeReputation>
deployContract(name: 'BansheeTicketMarketplace', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BansheeTicketMarketplace>
deployContract(name: 'IIdentityVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IIdentityVerifier>
deployContract(name: 'MockIdentityVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockIdentityVerifier>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  