/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockIdentityVerifierInterface extends Interface {
    getFunction(nameOrSignature: "setShouldVerify" | "shouldVerify" | "verify"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'setShouldVerify', values: [boolean]): string;
encodeFunctionData(functionFragment: 'shouldVerify', values?: undefined): string;
encodeFunctionData(functionFragment: 'verify', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'setShouldVerify', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shouldVerify', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify', data: BytesLike): Result;
  }

  

  export interface MockIdentityVerifier extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockIdentityVerifier;
    waitForDeployment(): Promise<this>;

    interface: MockIdentityVerifierInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    setShouldVerify: TypedContractMethod<
      [value: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    shouldVerify: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    verify: TypedContractMethod<
      [arg0: BytesLike, arg1: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'setShouldVerify'): TypedContractMethod<
      [value: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'shouldVerify'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'verify'): TypedContractMethod<
      [arg0: BytesLike, arg1: BytesLike, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }