/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IReputation, IReputationInterface } from "../../BansheeMining.sol/IReputation.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "artist",
        "type": "address"
      }
    ],
    "name": "reputation",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "chunksServed",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "uniqueFans",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "reputationScore",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IReputation__factory {
    static readonly abi = _abi;
    static createInterface(): IReputationInterface {
      return new Interface(_abi) as IReputationInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IReputation {
      return new Contract(address, _abi, runner) as unknown as IReputation;
    }
  }
  